name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches: [main]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Node dependencies
        run: pnpm install

      - name: Set Version Tag
        id: version
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION=${GITHUB_REF_NAME}
            IS_BETA=false
          else
            VERSION="dev-${GITHUB_SHA::7}"
            IS_BETA=true
          fi
          echo "VERSION=$VERSION"
          echo "IS_BETA=$IS_BETA" >> $GITHUB_OUTPUT

      - name: Build Application
        run: pnpm tauri build

    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.version.outputs.version }}
          path: |
            ./src-tauri/target/release/bundle/msi/*.msi
            ./src-tauri/target/release/bundle/nsis/*.exe
          if-no-files-found: error

      - name: Upload GitHub Release
        if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ./src-tauri/target/release/bundle/msi/*.msi
            ./src-tauri/target/release/bundle/nsis/*.exe
          prerelease: ${{ steps.version.outputs.IS_BETA }}  # Set prerelease flag based on `main` or stable tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
